#!/usr/bin/env ruby
=begin
  vim: sw=2:
  Copyright (c) 2019 Gennady Bystritsky <bystr@mac.com>

  Distributed under the MIT Licence.
  This is free software. See 'LICENSE' for details.
  You must read and accept the license prior to use.

  Author: Bystritsky, Gennady
=end

$:.concat ENV['PATH'].to_s.split(':')

require 'tsc/application.rb'
require 'tsc/path.rb'

class Application < TSC::Application
  def initialize
    super { |_config|
      _config.arguments = '<items> ...'
      _config.options = [
        [ '--parameter', 'A parameter', 'name', '-p', '-n' ],
        [ '--test', 'Run internal tests' ]
      ]
      _config.description = [
        "Converts Maven's pom.xml file to YAML representation."
      ]
    }
  end

  def start
    handle_errors {
      process_command_line
      require 'rubygems'

      throw :TEST if options.test?
    }
  end

  in_generator_context do |_content|
    _content << '#!' + figure_ruby_path
    _content << '$VERBOSE = nil'
    _content << TSC::PATH.current.front(File.dirname(figure_ruby_path)).to_ruby_eval
    _content << IO.readlines(__FILE__).slice(1..-1)
  end
end

unless defined? Test::Unit::TestCase
  catch :TEST do
    Application.new.start
    exit 0
  end
end

require 'rubygems'
require 'test/unit'
require 'mocha'

class ApplicationTest < Test::Unit::TestCase
  attr_reader :app

  def test_nothing
  end

  def setup
    @app = Application.new
  end
end
